on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Checkout the repository
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    # Install dependencies
    - run: |
        pip install -r requirements.txt
        
    # Test
    - name: Run tests
      run: |
        echo "Run tests"
        


    # Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Execute the Update Script on the VMSS
    - name: Deploy to Azure VMSS
      run: |
        az vmss extension set \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --vmss-name ${{ secrets.VMSS_NAME }} \
          --name CustomScript \
          --force-update \
          --publisher Microsoft.Azure.Extensions \
          --settings '{"commandToExecute": "chmod +x /home/azureuser/project6/SDA-Project-6/update_app.sh && /home/azureuser/project6/SDA-Project-6/update_app.sh"}'
